#My Python Story
import time
print("This is basically The Lord of the Flies! Would you like to play?")
response=input()
response=response.lower()

if response=='yes' or response=='sure':
    print("Great! Let's get started!")
    print(' ')
    time.sleep(2)
    print("You are stranded on an island with many other people.")
    print(' ')
    time.sleep(2)
    print("What do you do? (elect a leader/ relax on the beach)")
    print(' ')
    firstchoice=input()
    firstchoice=firstchoice.lower()
    
    if firstchoice=='elect a leader':
        print("Ok. You are elected as leader!")
        print(' ')
        time.sleep(2)
        print("What is your first priority right now? (start a fire/ go hunting)")
        print(' ')
        goodone=input()
        goodone=goodone.lower()

        if goodone=='start a fire' or goodone=='fire':
            print('Ok. A ship passes by, and you expect to be saved, but people who went hunting accidently let it go out. The ship leaves without seeing you.')
            print(' ')
            time.sleep(2)
            print('What do you do? (shout at the hunters for a bit/ ban them from the group)')
            print(' ')
            secondone=input()
            secondone=secondone.lower()
            
            if secondone=='shout at the hunters for a bit' or secondone=='shout':
                print('Ok. The hunters felt bad and decided they will try and keep the fire lit, rather than hunt.')
                print('  ')
                time.sleep(2)
                print('Finally, a ship finds you and takes you off the island.')
                print('   ')
                time.sleep(2)
                print('You all survive, get off the island, and live happy lives.')
                print('  ')
                time.sleep(2)
                print('The End.')
            else:
                print('When you ban the hunters from the group, they leave and start their own group. Even though you light a fire and they hunt, a ship never finds you.')
                print('  ')
                time.sleep(2)
                print('This is because you do not have  enough people to keep the fire going at all times.')
                print('  ')
                time.sleep(2)
                print('The End.')
                 
        else:
            print('As you are hunting, a ship passes by, but they dont see you.')
            print(' ')
            time.sleep(2)
            print('What do you do? (start a fire/ keep hunting)')
            more=input()
            more=more.lower()

            if more=='start a fire':
                print('This time, when a second ship passes by, it does see you.')
                print('  ')
                time.sleep(2)
                print('You all survive and get off the island safely.')
                print('  ')
                time.sleep(2)
                print('The End.')
            else:
                print('You go hunting again, and when more ships pass, there is no fire to signal to them.')
                print('  ')
                time.sleep(2)
                print('You and everyone there live until you die on the island.')
                print('  ')
                time.sleep(2)
                print('The End.')

    else:
        print("Ok. As you are relaxing a fight breaks out, and there's no leader to keep them in control. >:D") 
        print(' ')
        time.sleep(2)
        print("What do you do? (Try to break it up/ leave them alone)")
        goose=input()
        goose=goose.lower()

        if goose=='try to break it up' or goose=='break it up':
            print('Ok. You break up the fight, but one person (Jack) is very mad at you.')
            print('  ')
            time.sleep(2)
            print('He believes that he should be leader, and does not appreciate you going and acting like one.')
            print('  ')
            time.sleep(2)
            print('What do you do?(ban him from the group/ try electing a leader again)')
            print('  ')
            egg=input()
            egg=egg.lower()
            
            if egg=='try electing a leader again' or egg=='elect a leader again':
                print('Ok then. People elect you as leader, and now he is even more mad.')
                print('  ')
                time.sleep(2)
                print('He decides to go leave the group, and people who were loyal to him before follow him.')
                print('  ')
                time.sleep(2)
                print('What do you do now? (go join their group/ stay with the others in your group)')
                god=input()
                god=god.lower()

                if god=="stay with the others in your group" or god=='stay':
                    print('Ok. One day, as you are sleeping, Jack and all his friends come back.')
                    print('  ')
                    time.sleep(2)
                    print('They invade your group and hold you all hostage for a bit, but finally kill you.')
                    print('  ')
                    time.sleep(2)
                    print('They never get off the island either, because they are too busy hunting to light a fire.')
                    print('  ')
                    time.sleep(2)
                    print('The End.')
                    
                else:
                    print('Now that you have joined their group, you are not Leader anymore.')
                    print('  ')
                    time.sleep(2)
                    print('Jack , now that he is leader, is only focusing on hunting pigs, and doesnt start a fire to be recued.')
                    print('  ')
                    time.sleep(2)
                    print('You all stay on the island for the rest of your lives. You are never rescued and die an unhappy death on the island.')
                    print(' ')
                    time.sleep(2)
                    print('The End.')
                    
            else:
                print('Jack is very mad that you banned him from the group, and he storms off, saying that people who want to hunt can follow him.')
                print('  ')
                time.sleep(2)
                print('Most of the group follows him, and you are left with only three people.')
                print('  ')
                time.sleep(2)
                print('You and the others start your own fire and finally someone sees you and comes to rescue you.')
                print('  ')
                time.sleep(2)
                print('However, you dont know where Jack and the others are.')
                print('  ')
                time.sleep(2)
                print('What do you do? (leave without them/ wait for them)')
                yip=input()
                yip=yip.lower()

                if yip=='wait for them' or yip=='wait':
                    print('Ok. Jack and the others finally realize that there is help on the island.')
                    print('  ')
                    time.sleep(2)
                    print('When they see the rescuers, they suddenly forget about hunting, and are very happy that they can leave the island.')
                    print('  ')
                    time.sleep(2)
                    print('You all get off the island, and live happy lives.')
                    print('  ')
                    time.sleep(2)
                    print('The End.')
                else:
                    print('You leave without Jack and the others. They stay on the island, unaware that they could ever be saved.')
                    print('  ')
                    time.sleep(2)
                    print('You and your three friends go home, but you always feel guilty about leaving them behind. You get very sad and live an unhappy life, even though you escaped the island.')
                    print('  ')
                    time.sleep(2)
                    print('The End.')
                
        else:   
            print('The fight gets very brutal, and one boy (Jack) severely injures the other one.')
            print('  ')
            time.sleep(2)
            print('Jack believes that people need to hunt.')
            print('  ')
            time.sleep(2)
            print('He threatens to take control of the entire group and start hunting for food.')
            print('  ')
            time.sleep(2)
            print('What do you do? (try electing a leader again/ let Jack be leader)')
            print('  ')
            begin=input()
            begin=begin.lower()

            if begin=='try electing a leader again' or begin=='elect a leader':
                print('Ok then. People elect you as leader(mostly because they are scared of Jack). Now, Jack is mad again, because he could not be leader.')
                print('  ')
                time.sleep(2)
                print('He claims a couple boys are under his control because he was leader of the choir they were in before. He wants to take them as hunters.')
                print('  ')
                time.sleep(2)
                print('What do you do? (give him the kids/dont give him the kids)')
                story=input()
                story=story.lower()

                if story=='give him the kids':
                    print('Ok. Jack is happy that he has control of the little group, and he takes them to go hunting.')
                    print('  ')
                    time.sleep(2)
                    print('Now, you have food from hunting and a fire for being rescued.')
                    print('  ')
                    time.sleep(2)
                    print('A ship finds you after seeing the fire, and you all get off the island and live happy lives.')
                    print('  ')
                    time.sleep(2) 
                    print('The End.')
                    
                else:
                    print('Ok. Now Jack is really mad that you didnt give him control of the group.')
                    print('  ')
                    time.sleep(2)
                    print('In a fit of rage, he attacks you and stabs you with a knife he had, and you die promptly.')
                    print('  ')
                    time.sleep(2)
                    print('He then becomes Leader and focuses on hunting only. This means noone ever gets off the island, and everyone dies there.')
                    print('  ')
                    time.sleep(2)
                    print('The End')
                    
            else:
                print('Ok. Now that Jack is leader, he only focuses on hunting. He does not care about getting of the island because he believes that he can have a good life there.')
                print(' ')
                time.sleep(2)
                print('Because of this, whenever a plane or a ship passes by, the only thing you can do is throw pig bones at it and hope they notice you.') 
                print('  ')
                time.sleep(2)
                print('You cannot rebel because Jack is leader, and he keeps very strict control of what happens.')
                print('  ')
                time.sleep(2)
                print('You never get off the island and die an unhappy death with all of your friends(not really)after some time.')
                print('  ')
                time.sleep(2)
                print('The End.')
                
else:
    print("Ok, Goodbye...")
    print(' ')

   
